import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { calcularAtencionPersonalizada } from "../lib/fichaCitaDominio.ts";

const base = (personas=1, modalidad:"simultanea"|"consecutiva"="simultanea") => ({ personas, modalidad, confirmaDisponibilidad:true, componentes:Array.from({length:personas},(_,i)=>({persona:i+1,componentes:[{tipo:"manual" as const,nombre:`Servicio ${i+1}`,precio:100,duracion_min:60}]})) });
test("personalizada de una persona exige S/10",()=>{ const r=calcularAtencionPersonalizada(base()); assert.equal(r.ok,true); if(r.ok) assert.equal(r.adelantoRequerido,10); });
test("simultánea de tres personas usa la mayor duración y 50%",()=>{ const r=calcularAtencionPersonalizada(base(3)); assert.equal(r.ok,true); if(r.ok){assert.equal(r.duracionMin,60);assert.equal(r.adelantoRequerido,150);} });
test("consecutiva suma duración y varios componentes",()=>{const x=base(2,"consecutiva");x.componentes[0].componentes.push({tipo:"manual",nombre:"Extra",precio:50,duracion_min:30});const r=calcularAtencionPersonalizada(x);assert.equal(r.ok,true);if(r.ok)assert.equal(r.duracionMin,150);});
test("ajuste exige motivo y conserva calculado/final/diferencia",()=>{assert.equal(calcularAtencionPersonalizada({...base(),precioFinal:90}).ok,false);const r=calcularAtencionPersonalizada({...base(),precioFinal:90,motivoAjuste:"Cortesía"});assert.equal(r.ok,true);if(r.ok)assert.deepEqual([r.precioCalculado,r.precioFinal,r.diferencia],[100,90,-10]);});
test("rechaza más de cinco, componente inválido y falta de confirmación",()=>{assert.equal(calcularAtencionPersonalizada(base(6)).ok,false);assert.equal(calcularAtencionPersonalizada({...base(),confirmaDisponibilidad:false}).ok,false);assert.equal(calcularAtencionPersonalizada({...base(),componentes:[{persona:1,componentes:[{tipo:"manual",nombre:"",precio:0,duracion_min:0}]}]}).ok,false);});
test("migración 017 protege RPC, auditoría, restricciones e idempotencia",async()=>{const sql=await readFile(new URL("../sql/017_atenciones_personalizadas.sql",import.meta.url),"utf8");for(const token of ["security definer","set search_path=public","request_id","motivo_ajuste","responsable_ajuste","disponibilidad_confirmada","PERSONALIZADA_SOLO_DIRECTO_PRESENCIAL","revoke all","service_role"])assert.match(sql,new RegExp(token,"i"));});
test("GET versiona solo la personalizada y no expone auditoría",async()=>{const route=await readFile(new URL("../app/api/publico/ficha/[token]/route.ts",import.meta.url),"utf8");assert.match(route,/ficha-cita-v2/);assert.match(route,/componentesPorPersona/);assert.doesNotMatch(route,/motivo_ajuste|responsable_ajuste/);});
