-- ============================================================
-- Caja Vita Lima — Supabase SQL v1
-- Archivo: sql/001_create_tables.sql
-- Objetivo: crear la primera estructura de tablas para migrar
-- la Caja actual desde Google Apps Script / Google Sheets.
-- ============================================================

-- Recomendado para UUID si más adelante usamos ids automáticos.
create extension if not exists "pgcrypto";

-- ============================================================
-- 1) CONFIG_LISTAS
-- Equivalente a hoja: CONFIG_LISTAS
-- ============================================================
create table if not exists public.config_listas (
  id bigint generated by default as identity primary key,
  lista text not null,
  valor text not null,
  orden integer,
  activo boolean default true,
  alias_de text,
  nota text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_config_listas_lista on public.config_listas(lista);
create index if not exists idx_config_listas_activo on public.config_listas(activo);

-- ============================================================
-- 2) USUARIOS
-- Equivalente a hoja: USUARIOS
-- Nota: en una fase posterior el login real debe pasar a Supabase Auth.
-- ============================================================
create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  usuario text unique not null,
  pin text,
  rol text not null,
  nombre text,
  activo boolean default true,
  nota text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_usuarios_rol on public.usuarios(rol);
create index if not exists idx_usuarios_activo on public.usuarios(activo);

-- ============================================================
-- 3) CLIENTES
-- Equivalente a hoja: CLIENTES
-- ============================================================
create table if not exists public.clientes (
  cliente_id text primary key,
  cliente text,
  whatsapp text,
  dni text,
  email text,
  ultima_sede text,
  ultima_visita date,
  ultimo_servicio text,
  notas text,
  origen text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  total_reservas integer default 0,
  primera_reserva date,
  ultima_reserva date,
  cliente_potencial text,
  segmento_cliente text
);

create index if not exists idx_clientes_whatsapp on public.clientes(whatsapp);
create index if not exists idx_clientes_dni on public.clientes(dni);
create index if not exists idx_clientes_cliente on public.clientes(cliente);
create index if not exists idx_clientes_segmento on public.clientes(segmento_cliente);

-- ============================================================
-- 4) CITAS_RESERVADAS
-- Equivalente a hoja: CITAS_RESERVADAS
-- ============================================================
create table if not exists public.citas_reservadas (
  reserva_id text primary key,
  fecha_cita date,
  hora_cita time,
  sede text,
  cliente_id text,
  cliente text,
  dni text,
  whatsapp text,
  n_pax integer default 1,
  servicio text,
  duracion text,
  monto_total numeric(12,2) default 0,
  adelanto numeric(12,2) default 0,
  metodo_adelanto text,
  saldo_pendiente numeric(12,2) default 0,
  estado text default 'PENDIENTE',
  source text,
  source_id text,
  service_code text,
  servicio_detalle text,
  calendar_description text,
  calendar_status text,
  calendar_event_id text,
  calendar_link text,
  calendar_error text,
  calendar_created_at timestamptz,
  observacion text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_citas_fecha on public.citas_reservadas(fecha_cita);
create index if not exists idx_citas_sede on public.citas_reservadas(sede);
create index if not exists idx_citas_estado on public.citas_reservadas(estado);
create index if not exists idx_citas_cliente_id on public.citas_reservadas(cliente_id);
create index if not exists idx_citas_whatsapp on public.citas_reservadas(whatsapp);
create index if not exists idx_citas_calendar_event_id on public.citas_reservadas(calendar_event_id);

-- ============================================================
-- 5) CAJA_MOVIMIENTOS
-- Equivalente a hoja: CAJA_MOVIMIENTOS
-- ============================================================
create table if not exists public.caja_movimientos (
  movimiento_id text primary key,
  fecha date,
  hora time,
  sede text,
  tipo_movimiento text,
  estado text default 'Registrado',
  cliente_id text,
  cliente text,
  whatsapp text,
  dni text,
  n_pax integer default 1,
  servicio text,
  duracion text,
  monto_servicio numeric(12,2) default 0,
  adelanto_prev numeric(12,2) default 0,
  metodo_adelanto_prev text,
  total_cobrar numeric(12,2) default 0,
  total_pagado numeric(12,2) default 0,
  total_extras numeric(12,2) default 0,
  pendiente numeric(12,2) default 0,
  estado_boleta text,
  numero_boleta text,
  responsable text,
  source_type text,
  source_id text,
  observacion text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_mov_fecha on public.caja_movimientos(fecha);
create index if not exists idx_mov_sede on public.caja_movimientos(sede);
create index if not exists idx_mov_tipo on public.caja_movimientos(tipo_movimiento);
create index if not exists idx_mov_cliente_id on public.caja_movimientos(cliente_id);
create index if not exists idx_mov_whatsapp on public.caja_movimientos(whatsapp);
create index if not exists idx_mov_estado_boleta on public.caja_movimientos(estado_boleta);
create index if not exists idx_mov_source on public.caja_movimientos(source_type, source_id);

-- ============================================================
-- 6) CAJA_PAGOS
-- Equivalente a hoja: CAJA_PAGOS
-- ============================================================
create table if not exists public.caja_pagos (
  pago_id text primary key,
  movimiento_id text,
  fecha date,
  hora time,
  sede text,
  tipo_pago text,
  metodo text,
  metodo_detalle text,
  monto numeric(12,2) default 0,
  concepto text,
  created_at timestamptz default now()
);

create index if not exists idx_pagos_movimiento_id on public.caja_pagos(movimiento_id);
create index if not exists idx_pagos_fecha on public.caja_pagos(fecha);
create index if not exists idx_pagos_sede on public.caja_pagos(sede);
create index if not exists idx_pagos_metodo on public.caja_pagos(metodo);

-- ============================================================
-- 7) CAJA_ATENCION_DETALLE
-- Equivalente a hoja: CAJA_ATENCION_DETALLE
-- ============================================================
create table if not exists public.caja_atencion_detalle (
  detalle_id text primary key,
  movimiento_id text,
  fecha date,
  sede text,
  persona_n integer,
  terapista text,
  terapista_otro text,
  servicio text,
  duracion text,
  monto_asignado numeric(12,2) default 0,
  observacion text,
  created_at timestamptz default now()
);

create index if not exists idx_detalle_movimiento_id on public.caja_atencion_detalle(movimiento_id);
create index if not exists idx_detalle_fecha on public.caja_atencion_detalle(fecha);
create index if not exists idx_detalle_terapista on public.caja_atencion_detalle(terapista);

-- ============================================================
-- 8) GIFT_CARDS
-- Equivalente a hoja: GIFT_CARDS
-- ============================================================
create table if not exists public.gift_cards (
  giftcard_id text primary key,
  fecha_venta date,
  comprador text,
  whatsapp_comprador text,
  destinatario text,
  n_pax integer default 1,
  servicio text,
  duracion text,
  monto numeric(12,2) default 0,
  metodo_pago text,
  fecha_uso date,
  estado text default 'VENDIDA',
  anotado_en_caja text,
  observacion text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_gift_fecha_venta on public.gift_cards(fecha_venta);
create index if not exists idx_gift_whatsapp on public.gift_cards(whatsapp_comprador);
create index if not exists idx_gift_estado on public.gift_cards(estado);

-- ============================================================
-- 9) CUPONES_CONVENIOS
-- Equivalente a hoja: CUPONES_CONVENIOS
-- ============================================================
create table if not exists public.cupones_convenios (
  registro_id text primary key,
  fecha date,
  hora time,
  sede text,
  plataforma text,
  codigo_cupon text,
  cliente text,
  whatsapp text,
  n_pax integer default 1,
  servicio text,
  monto_reconocido numeric(12,2) default 0,
  monto_cobrado_tienda numeric(12,2) default 0,
  metodo_pago_tienda text,
  estado_boleta text,
  numero_boleta text,
  responsable text,
  observacion text,
  created_at timestamptz default now()
);

create index if not exists idx_cupones_fecha on public.cupones_convenios(fecha);
create index if not exists idx_cupones_sede on public.cupones_convenios(sede);
create index if not exists idx_cupones_whatsapp on public.cupones_convenios(whatsapp);
create index if not exists idx_cupones_plataforma on public.cupones_convenios(plataforma);

-- ============================================================
-- 10) CAJA_SALIDAS
-- Equivalente a hoja: CAJA_SALIDAS
-- ============================================================
create table if not exists public.caja_salidas (
  salida_id text primary key,
  fecha date,
  hora time,
  sede text,
  tipo_gasto text,
  concepto text,
  monto numeric(12,2) default 0,
  responsable text,
  source_movimiento_id text,
  observacion text,
  created_at timestamptz default now()
);

create index if not exists idx_salidas_fecha on public.caja_salidas(fecha);
create index if not exists idx_salidas_sede on public.caja_salidas(sede);
create index if not exists idx_salidas_tipo_gasto on public.caja_salidas(tipo_gasto);

-- ============================================================
-- 11) CAJA_CIERRES
-- Equivalente a hoja: CAJA_CIERRES
-- ============================================================
create table if not exists public.caja_cierres (
  cierre_id text primary key,
  fecha date,
  sede text,
  caja_inicial numeric(12,2) default 0,
  efectivo_contado numeric(12,2) default 0,
  pozo_fondo numeric(12,2) default 0,
  total_ingresos numeric(12,2) default 0,
  total_salidas numeric(12,2) default 0,
  caja_esperada numeric(12,2) default 0,
  diferencia numeric(12,2) default 0,
  pax_total integer default 0,
  boletas_pendientes integer default 0,
  responsable text,
  estado text default 'CERRADO',
  observacion text,
  created_at timestamptz default now()
);

create index if not exists idx_cierres_fecha on public.caja_cierres(fecha);
create index if not exists idx_cierres_sede on public.caja_cierres(sede);
create index if not exists idx_cierres_estado on public.caja_cierres(estado);

-- ============================================================
-- 12) VISTAS INICIALES
-- Estas vistas ayudan a la futura app y al dashboard.
-- ============================================================

create or replace view public.vista_citas_con_cliente as
select
  c.*,
  cl.total_reservas,
  cl.segmento_cliente,
  cl.cliente_potencial,
  cl.primera_reserva,
  cl.ultima_reserva,
  cl.ultima_visita,
  cl.ultimo_servicio,
  cl.ultima_sede
from public.citas_reservadas c
left join public.clientes cl
  on cl.cliente_id = c.cliente_id;

create or replace view public.vista_movimientos_dashboard as
select
  m.movimiento_id,
  m.fecha,
  m.hora,
  m.sede,
  m.tipo_movimiento,
  m.estado,
  m.cliente_id,
  m.cliente,
  m.whatsapp,
  m.dni,
  m.n_pax,
  m.servicio,
  m.duracion,
  m.monto_servicio,
  m.adelanto_prev,
  m.total_cobrar,
  m.total_pagado,
  m.total_extras,
  m.pendiente,
  m.estado_boleta,
  m.numero_boleta,
  m.responsable,
  m.source_type,
  m.source_id,
  m.created_at,
  m.updated_at
from public.caja_movimientos m;

-- ============================================================
-- 13) DATOS BASE OPCIONALES
-- Inserta configuración mínima si la tabla está vacía.
-- ============================================================

insert into public.config_listas (lista, valor, orden, activo, alias_de, nota)
select * from (values
  ('SEDES', 'Miraflores', 1, true, '', ''),
  ('SEDES', 'San Borja', 2, true, '', ''),
  ('METODOS_PAGO', 'EFECTIVO', 1, true, '', ''),
  ('METODOS_PAGO', 'YAPE', 2, true, '', ''),
  ('METODOS_PAGO', 'PLIN', 3, true, '', ''),
  ('METODOS_PAGO', 'BCP', 4, true, '', ''),
  ('METODOS_PAGO', 'INTERBANK', 5, true, '', ''),
  ('METODOS_PAGO', 'SCOTIABANK', 6, true, '', ''),
  ('METODOS_PAGO', 'BBVA', 7, true, '', ''),
  ('METODOS_PAGO', 'IZIPAY POS', 8, true, '', ''),
  ('METODOS_PAGO', 'LINK IZIPAY', 9, true, '', ''),
  ('METODOS_PAGO', 'OTRO', 10, true, '', ''),
  ('ESTADO_BOLETA', 'Emitida', 1, true, '', ''),
  ('ESTADO_BOLETA', 'Pendiente', 2, true, '', ''),
  ('ESTADO_BOLETA', 'No aplica', 3, true, '', ''),
  ('ESTADO_BOLETA', 'Anulada', 4, true, '', ''),
  ('RESPONSABLES', 'Gerald', 1, true, '', ''),
  ('RESPONSABLES', 'Luis', 2, true, '', ''),
  ('RESPONSABLES', 'Naty', 3, true, '', ''),
  ('RESPONSABLES', 'Nataly', 4, true, '', ''),
  ('RESPONSABLES', 'Otro', 5, true, '', '')
) as v(lista, valor, orden, activo, alias_de, nota)
where not exists (select 1 from public.config_listas);

insert into public.usuarios (usuario, pin, rol, nombre, activo, nota)
select * from (values
  ('gerald', '1234', 'ADMIN_GERALD', 'Gerald', true, 'Administrador técnico y operativo'),
  ('luis', '1234', 'CAJA', 'Luis', true, 'Caja / pagos'),
  ('naty', '1234', 'CAJA', 'Naty', true, 'Citas / atención'),
  ('socio', '1234', 'FINANZAS', 'Socio', true, 'Dashboard y reportes')
) as v(usuario, pin, rol, nombre, activo, nota)
where not exists (select 1 from public.usuarios);

-- ============================================================
-- FIN DEL SCRIPT
-- ============================================================
