-- ============================================================
-- Caja Vita Lima — Ficha personal ampliada de terapistas
-- Migración 030
-- Requiere: 029_terapistas_maestro_ficha.sql
-- ============================================================

-- Datos personales y de contacto. Se separan del maestro operativo para
-- no mezclar identidad/estado con información privada de RR. HH.
create table if not exists public.terapista_datos_personales (
  terapista_id uuid primary key references public.terapistas(terapista_id) on delete restrict,
  nombre_completo text,
  direccion text,
  fecha_nacimiento date,
  dni text,
  ruc text,
  estado_civil text,
  hijos integer check (hijos is null or hijos >= 0),
  correo text,
  contacto_emergencia text,
  telefono_emergencia text,
  relacion_contacto text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint terapista_datos_personales_dni_chk
    check (dni is null or dni ~ '^[0-9]{8}$'),
  constraint terapista_datos_personales_ruc_chk
    check (ruc is null or ruc ~ '^[0-9]{11}$')
);

-- Datos laborales complementarios al maestro. Fecha de ingreso y sede
-- habitual siguen viviendo en public.terapistas para uso operativo.
create table if not exists public.terapista_datos_laborales (
  terapista_id uuid primary key references public.terapistas(terapista_id) on delete restrict,
  codigo_marcacion text,
  llaves boolean,
  observacion_laboral text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint terapista_datos_laborales_codigo_chk
    check (codigo_marcacion is null or codigo_marcacion ~ '^[0-9]{4}$')
);

-- Información financiera separada para poder limitar su exposición en UI.
create table if not exists public.terapista_datos_pago (
  terapista_id uuid primary key references public.terapistas(terapista_id) on delete restrict,
  banco text,
  cuenta_soles text,
  afp text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Uniforme: una fila por prenda. Permite talla y cantidad sin agregar columnas
-- cada vez que aparezca una nueva prenda.
create table if not exists public.terapista_uniforme (
  uniforme_id bigint generated by default as identity primary key,
  terapista_id uuid not null references public.terapistas(terapista_id) on delete restrict,
  prenda text not null,
  talla text,
  cantidad integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint terapista_uniforme_cantidad_chk
    check (cantidad is null or cantidad > 0),
  constraint terapista_uniforme_unique unique (terapista_id, prenda)
);

create index if not exists idx_terapista_uniforme_terapista
  on public.terapista_uniforme(terapista_id);

-- Crear filas vacías para las fichas actuales. Es idempotente y no pisa datos.
insert into public.terapista_datos_personales (terapista_id)
select terapista_id from public.terapistas
on conflict (terapista_id) do nothing;

insert into public.terapista_datos_laborales (terapista_id)
select terapista_id from public.terapistas
on conflict (terapista_id) do nothing;

insert into public.terapista_datos_pago (terapista_id)
select terapista_id from public.terapistas
on conflict (terapista_id) do nothing;

-- Validaciones sugeridas post-migración:
-- select * from public.terapista_datos_personales order by terapista_id;
-- select * from public.terapista_datos_laborales order by terapista_id;
-- select * from public.terapista_datos_pago order by terapista_id;
-- select * from public.terapista_uniforme order by terapista_id, prenda;
