-- ============================================================
-- Caja Vita Lima — Horario habitual de terapistas
-- Migración 031
-- Requiere: 029_terapistas_maestro_ficha.sql
-- ============================================================

create table if not exists public.terapista_horario_habitual (
  horario_id bigint generated by default as identity primary key,
  terapista_id uuid not null references public.terapistas(terapista_id) on delete restrict,
  dia_semana smallint not null,
  trabaja boolean not null default false,
  hora_inicio time,
  hora_fin time,
  sede text,
  observacion text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint terapista_horario_habitual_dia_chk check (dia_semana between 1 and 7),
  constraint terapista_horario_habitual_horas_chk check (
    (trabaja = false and hora_inicio is null and hora_fin is null)
    or
    (trabaja = true and hora_inicio is not null and hora_fin is not null and hora_fin > hora_inicio)
  ),
  constraint terapista_horario_habitual_unique unique (terapista_id, dia_semana)
);

create index if not exists idx_terapista_horario_habitual_terapista
  on public.terapista_horario_habitual(terapista_id, dia_semana);

-- Crea los 7 días para cada terapista existente sin pisar configuraciones futuras.
insert into public.terapista_horario_habitual (terapista_id, dia_semana, trabaja)
select t.terapista_id, d.dia_semana, false
from public.terapistas t
cross join (values (1),(2),(3),(4),(5),(6),(7)) as d(dia_semana)
on conflict (terapista_id, dia_semana) do nothing;

-- Validación sugerida post-migración:
-- select t.nombre, h.*
-- from public.terapista_horario_habitual h
-- join public.terapistas t on t.terapista_id = h.terapista_id
-- order by t.nombre, h.dia_semana;
