-- ============================================================
-- Caja Vita Lima — Excepciones de horario por fecha
-- Migración 032
-- Requiere: 029_terapistas_maestro_ficha.sql
-- ============================================================

create table if not exists public.terapista_horario_excepciones (
  excepcion_id bigint generated by default as identity primary key,
  terapista_id uuid not null references public.terapistas(terapista_id) on delete restrict,
  fecha date not null,
  tipo text not null,
  trabaja boolean not null default false,
  hora_inicio time,
  hora_fin time,
  sede text,
  observacion text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint terapista_horario_excepciones_tipo_chk check (
    tipo in (
      'DESCANSO',
      'CAMBIO_HORARIO',
      'FALTA',
      'RECUPERACION',
      'VACACIONES',
      'REUNION',
      'APOYO'
    )
  ),
  constraint terapista_horario_excepciones_horas_chk check (
    (trabaja = false and hora_inicio is null and hora_fin is null)
    or
    (trabaja = true and hora_inicio is not null and hora_fin is not null and hora_fin > hora_inicio)
  ),
  constraint terapista_horario_excepciones_unique unique (terapista_id, fecha)
);

create index if not exists idx_terapista_horario_excepciones_fecha
  on public.terapista_horario_excepciones(fecha, terapista_id);

create index if not exists idx_terapista_horario_excepciones_terapista
  on public.terapista_horario_excepciones(terapista_id, fecha desc);

-- Validación sugerida post-migración:
-- select t.nombre, e.*
-- from public.terapista_horario_excepciones e
-- join public.terapistas t on t.terapista_id = e.terapista_id
-- order by e.fecha, t.nombre;
