-- 034 · Ingesta idempotente de clientes desde Google Form y outbox Google Contacts.
--
-- Arquitectura:
-- Google Form -> Google Sheet -> n8n -> caja_ingestar_cliente_form_v1()
-- -> public.clientes (maestro) -> cliente_contact_sync_outbox -> Google Contacts.
--
-- Reglas:
-- - clientes sigue siendo la fuente maestra.
-- - nunca se infiere país en SQL.
-- - solo un teléfono CANONICO puede encolarse a Google Contacts.
-- - respuestas ambiguas/conflictivas quedan trazadas pero no crean contactos.
-- - source_record_id hace la ingesta idempotente.

create table if not exists public.cliente_form_ingestas (
  ingesta_id bigint generated by default as identity primary key,
  source_system text not null default 'GOOGLE_FORM',
  source_record_id text not null,
  source_sheet text,
  source_row integer,
  source_submitted_at timestamptz,
  payload_hash text not null,
  raw_payload jsonb not null default '{}'::jsonb,
  cliente_nombre text,
  whatsapp_raw text,
  whatsapp_e164 text,
  pais_telefono text,
  telefono_estado text not null default 'PENDIENTE_REVISION',
  dni text,
  email text,
  fecha_nacimiento date,
  cliente_id text references public.clientes(cliente_id) on update cascade on delete set null,
  estado text not null default 'PENDING',
  decision text,
  error_code text,
  error_detail text,
  attempts integer not null default 0,
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_cliente_form_ingestas_source unique (source_system, source_record_id),
  constraint chk_cliente_form_ingestas_estado check (estado in (
    'PENDING','PROCESSING','SUCCEEDED','PENDIENTE_REVISION','FAILED'
  )),
  constraint chk_cliente_form_ingestas_telefono_estado check (telefono_estado in (
    'CANONICO','PENDIENTE_REVISION','SIN_TELEFONO'
  ))
);

create index if not exists idx_cliente_form_ingestas_estado
  on public.cliente_form_ingestas (estado, updated_at, ingesta_id);
create index if not exists idx_cliente_form_ingestas_cliente
  on public.cliente_form_ingestas (cliente_id, updated_at desc);

create table if not exists public.cliente_contact_sync_outbox (
  sync_id bigint generated by default as identity primary key,
  cliente_id text not null references public.clientes(cliente_id) on update cascade on delete cascade,
  provider text not null default 'GOOGLE_CONTACTS',
  estado text not null default 'PENDING',
  payload_hash text not null,
  resource_name text,
  attempts integer not null default 0,
  lease_until timestamptz,
  next_retry_at timestamptz,
  last_error text,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_cliente_contact_sync_provider unique (cliente_id, provider),
  constraint chk_cliente_contact_sync_estado check (estado in (
    'PENDING','PROCESSING','SUCCEEDED','FAILED','DEAD','SKIPPED'
  )),
  constraint chk_cliente_contact_sync_provider check (provider in ('GOOGLE_CONTACTS')),
  constraint chk_cliente_contact_sync_attempts check (attempts >= 0)
);

create index if not exists idx_cliente_contact_sync_pendientes
  on public.cliente_contact_sync_outbox (estado, next_retry_at, lease_until, sync_id)
  where estado in ('PENDING','FAILED','PROCESSING');

alter table public.cliente_form_ingestas enable row level security;
alter table public.cliente_contact_sync_outbox enable row level security;
revoke all on table public.cliente_form_ingestas from anon, authenticated;
revoke all on table public.cliente_contact_sync_outbox from anon, authenticated;
grant all on table public.cliente_form_ingestas to service_role;
grant all on table public.cliente_contact_sync_outbox to service_role;
grant usage, select on sequence public.cliente_form_ingestas_ingesta_id_seq to service_role;
grant usage, select on sequence public.cliente_contact_sync_outbox_sync_id_seq to service_role;

create or replace function public.caja_ingestar_cliente_form_v1(
  p_source_record_id text,
  p_source_sheet text,
  p_source_row integer,
  p_source_submitted_at timestamptz,
  p_cliente_nombre text,
  p_whatsapp_raw text,
  p_whatsapp_e164 text,
  p_pais_telefono text,
  p_telefono_estado text,
  p_dni text default null,
  p_email text default null,
  p_fecha_nacimiento date default null,
  p_raw_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_source_record_id text := nullif(btrim(p_source_record_id), '');
  v_nombre text := nullif(btrim(p_cliente_nombre), '');
  v_whatsapp_raw text := nullif(btrim(p_whatsapp_raw), '');
  v_e164 text := nullif(btrim(p_whatsapp_e164), '');
  v_pais text := nullif(upper(btrim(p_pais_telefono)), '');
  v_dni text := nullif(btrim(p_dni), '');
  v_email text := nullif(lower(btrim(p_email)), '');
  v_tel_estado text := coalesce(nullif(upper(btrim(p_telefono_estado)), ''), 'PENDIENTE_REVISION');
  v_payload_hash text := md5(coalesce(p_raw_payload, '{}'::jsonb)::text);
  v_ingesta public.cliente_form_ingestas%rowtype;
  v_cliente public.clientes%rowtype;
  v_conflicto_id text;
  v_cliente_id text;
  v_contact_hash text;
begin
  if v_source_record_id is null then
    raise exception 'CAJA_FORM_SOURCE_ID_REQUIRED';
  end if;

  insert into public.cliente_form_ingestas (
    source_system, source_record_id, source_sheet, source_row, source_submitted_at,
    payload_hash, raw_payload, cliente_nombre, whatsapp_raw, whatsapp_e164,
    pais_telefono, telefono_estado, dni, email, fecha_nacimiento,
    estado, attempts, updated_at
  ) values (
    'GOOGLE_FORM', v_source_record_id, nullif(btrim(p_source_sheet), ''), p_source_row,
    p_source_submitted_at, v_payload_hash, coalesce(p_raw_payload, '{}'::jsonb),
    v_nombre, v_whatsapp_raw, v_e164, v_pais, v_tel_estado, v_dni, v_email,
    p_fecha_nacimiento, 'PROCESSING', 1, now()
  )
  on conflict (source_system, source_record_id) do update set
    source_sheet = excluded.source_sheet,
    source_row = excluded.source_row,
    source_submitted_at = excluded.source_submitted_at,
    payload_hash = excluded.payload_hash,
    raw_payload = excluded.raw_payload,
    cliente_nombre = excluded.cliente_nombre,
    whatsapp_raw = excluded.whatsapp_raw,
    whatsapp_e164 = excluded.whatsapp_e164,
    pais_telefono = excluded.pais_telefono,
    telefono_estado = excluded.telefono_estado,
    dni = excluded.dni,
    email = excluded.email,
    fecha_nacimiento = excluded.fecha_nacimiento,
    estado = case
      when public.cliente_form_ingestas.estado = 'SUCCEEDED'
       and public.cliente_form_ingestas.payload_hash = excluded.payload_hash
      then 'SUCCEEDED'
      else 'PROCESSING'
    end,
    attempts = case
      when public.cliente_form_ingestas.payload_hash = excluded.payload_hash
      then public.cliente_form_ingestas.attempts
      else public.cliente_form_ingestas.attempts + 1
    end,
    error_code = null,
    error_detail = null,
    updated_at = now()
  returning * into v_ingesta;

  if v_ingesta.estado = 'SUCCEEDED' and v_ingesta.payload_hash = v_payload_hash and v_ingesta.cliente_id is not null then
    return jsonb_build_object(
      'ok', true,
      'idempotent', true,
      'estado', 'SUCCEEDED',
      'decision', v_ingesta.decision,
      'cliente_id', v_ingesta.cliente_id,
      'contacts_enqueued', true
    );
  end if;

  if v_tel_estado <> 'CANONICO'
     or v_e164 is null
     or v_e164 !~ '^\+[1-9][0-9]{7,14}$'
     or v_pais is null
     or v_pais !~ '^[A-Z]{2}$' then
    update public.cliente_form_ingestas
    set estado = 'PENDIENTE_REVISION',
        decision = 'NO_CANONICO',
        error_code = 'TELEFONO_NO_CANONICO',
        error_detail = 'Se conserva la respuesta, pero no se crea/actualiza cliente ni Google Contact.',
        processed_at = now(),
        updated_at = now()
    where ingesta_id = v_ingesta.ingesta_id;

    return jsonb_build_object(
      'ok', true,
      'estado', 'PENDIENTE_REVISION',
      'decision', 'NO_CANONICO',
      'cliente_id', null,
      'contacts_enqueued', false
    );
  end if;

  select * into v_cliente
  from public.clientes
  where whatsapp_e164 = v_e164
  limit 1;

  if v_cliente.cliente_id is null then
    if v_dni is not null then
      select cliente_id into v_conflicto_id
      from public.clientes
      where nullif(btrim(dni), '') is not null
        and lower(btrim(dni)) = lower(v_dni)
      limit 1;
    end if;

    if v_conflicto_id is null and v_email is not null then
      select cliente_id into v_conflicto_id
      from public.clientes
      where nullif(btrim(email), '') is not null
        and lower(btrim(email)) = v_email
      limit 1;
    end if;

    if v_conflicto_id is not null then
      update public.cliente_form_ingestas
      set estado = 'PENDIENTE_REVISION',
          decision = 'CONFLICTO_IDENTIDAD',
          error_code = 'IDENTIDAD_EXISTENTE_OTRO_WHATSAPP',
          error_detail = 'DNI o email ya pertenece a otra ficha; requiere revisión manual.',
          cliente_id = v_conflicto_id,
          processed_at = now(),
          updated_at = now()
      where ingesta_id = v_ingesta.ingesta_id;

      return jsonb_build_object(
        'ok', true,
        'estado', 'PENDIENTE_REVISION',
        'decision', 'CONFLICTO_IDENTIDAD',
        'cliente_id', v_conflicto_id,
        'contacts_enqueued', false
      );
    end if;

    v_cliente_id := 'CLI-FRM-' || upper(substr(md5(v_e164), 1, 12));

    insert into public.clientes (
      cliente_id, cliente, whatsapp, dni, email, fecha_nacimiento, origen,
      whatsapp_e164, pais_telefono, telefono_estado,
      telefono_normalizacion_origen, telefono_normalizado_en
    ) values (
      v_cliente_id,
      coalesce(v_nombre, 'Cliente ' || v_e164),
      coalesce(v_whatsapp_raw, v_e164),
      v_dni,
      v_email,
      p_fecha_nacimiento,
      'GOOGLE_FORM_N8N',
      v_e164,
      v_pais,
      'CANONICO',
      'APP_PAIS_DECLARADO',
      now()
    )
    returning * into v_cliente;

    update public.cliente_form_ingestas
    set cliente_id = v_cliente.cliente_id,
        estado = 'SUCCEEDED',
        decision = 'INSERTED',
        processed_at = now(),
        updated_at = now()
    where ingesta_id = v_ingesta.ingesta_id;
  else
    update public.clientes
    set cliente = case
          when (cliente is null or btrim(cliente) = '' or cliente ~ '^Cliente \+') and v_nombre is not null
          then v_nombre else cliente end,
        dni = coalesce(nullif(btrim(dni), ''), v_dni),
        email = coalesce(nullif(btrim(email), ''), v_email),
        fecha_nacimiento = coalesce(fecha_nacimiento, p_fecha_nacimiento),
        updated_at = now()
    where cliente_id = v_cliente.cliente_id
    returning * into v_cliente;

    update public.cliente_form_ingestas
    set cliente_id = v_cliente.cliente_id,
        estado = 'SUCCEEDED',
        decision = 'UPDATED',
        processed_at = now(),
        updated_at = now()
    where ingesta_id = v_ingesta.ingesta_id;
  end if;

  v_contact_hash := md5(concat_ws('|',
    coalesce(v_cliente.cliente, ''),
    coalesce(v_cliente.whatsapp_e164, ''),
    coalesce(v_cliente.email, ''),
    coalesce(v_cliente.fecha_nacimiento::text, '')
  ));

  insert into public.cliente_contact_sync_outbox (
    cliente_id, provider, estado, payload_hash, attempts, lease_until,
    next_retry_at, last_error, updated_at
  ) values (
    v_cliente.cliente_id, 'GOOGLE_CONTACTS', 'PENDING', v_contact_hash, 0,
    null, null, null, now()
  )
  on conflict (cliente_id, provider) do update set
    payload_hash = excluded.payload_hash,
    estado = case
      when public.cliente_contact_sync_outbox.payload_hash is distinct from excluded.payload_hash
        then 'PENDING'
      when public.cliente_contact_sync_outbox.estado in ('FAILED','DEAD','SKIPPED')
        then 'PENDING'
      else public.cliente_contact_sync_outbox.estado
    end,
    attempts = case
      when public.cliente_contact_sync_outbox.payload_hash is distinct from excluded.payload_hash
        then 0
      else public.cliente_contact_sync_outbox.attempts
    end,
    lease_until = null,
    next_retry_at = null,
    last_error = null,
    updated_at = now();

  return jsonb_build_object(
    'ok', true,
    'estado', 'SUCCEEDED',
    'decision', (select decision from public.cliente_form_ingestas where ingesta_id = v_ingesta.ingesta_id),
    'cliente_id', v_cliente.cliente_id,
    'contacts_enqueued', true
  );
exception
  when others then
    update public.cliente_form_ingestas
    set estado = 'FAILED',
        error_code = sqlstate,
        error_detail = left(sqlerrm, 1000),
        processed_at = now(),
        updated_at = now()
    where source_system = 'GOOGLE_FORM'
      and source_record_id = v_source_record_id;
    raise;
end;
$$;

revoke all on function public.caja_ingestar_cliente_form_v1(
  text,text,integer,timestamptz,text,text,text,text,text,text,text,date,jsonb
) from public, anon, authenticated;
grant execute on function public.caja_ingestar_cliente_form_v1(
  text,text,integer,timestamptz,text,text,text,text,text,text,text,date,jsonb
) to service_role;

create or replace function public.caja_contact_sync_claim_v1(
  p_limit integer default 10,
  p_lease_seconds integer default 300
)
returns table (
  sync_id bigint,
  cliente_id text,
  cliente text,
  whatsapp_e164 text,
  email text,
  fecha_nacimiento date,
  resource_name text,
  attempts integer,
  payload_hash text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with candidatos as (
    select o.sync_id
    from public.cliente_contact_sync_outbox o
    where (
      o.estado in ('PENDING','FAILED')
      or (o.estado = 'PROCESSING' and o.lease_until < now())
    )
      and (o.next_retry_at is null or o.next_retry_at <= now())
      and (o.lease_until is null or o.lease_until < now())
    order by o.updated_at, o.sync_id
    for update skip locked
    limit least(greatest(coalesce(p_limit, 10), 1), 100)
  ), reclamados as (
    update public.cliente_contact_sync_outbox o
    set estado = 'PROCESSING',
        attempts = o.attempts + 1,
        lease_until = now() + make_interval(secs => least(greatest(coalesce(p_lease_seconds, 300), 30), 1800)),
        updated_at = now()
    from candidatos c
    where o.sync_id = c.sync_id
    returning o.*
  )
  select
    r.sync_id,
    r.cliente_id,
    c.cliente,
    c.whatsapp_e164,
    c.email,
    c.fecha_nacimiento,
    r.resource_name,
    r.attempts,
    r.payload_hash
  from reclamados r
  join public.clientes c on c.cliente_id = r.cliente_id
  where c.telefono_estado = 'CANONICO'
    and c.whatsapp_e164 ~ '^\+[1-9][0-9]{7,14}$';
end;
$$;

revoke all on function public.caja_contact_sync_claim_v1(integer,integer) from public, anon, authenticated;
grant execute on function public.caja_contact_sync_claim_v1(integer,integer) to service_role;

create or replace function public.caja_contact_sync_finish_v1(
  p_sync_id bigint,
  p_ok boolean,
  p_resource_name text default null,
  p_error text default null,
  p_retry_seconds integer default 300
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.cliente_contact_sync_outbox%rowtype;
begin
  select * into v_row
  from public.cliente_contact_sync_outbox
  where sync_id = p_sync_id
  for update;

  if v_row.sync_id is null then
    raise exception 'CAJA_CONTACT_SYNC_NOT_FOUND';
  end if;

  if p_ok then
    update public.cliente_contact_sync_outbox
    set estado = 'SUCCEEDED',
        resource_name = coalesce(nullif(btrim(p_resource_name), ''), resource_name),
        lease_until = null,
        next_retry_at = null,
        last_error = null,
        last_synced_at = now(),
        updated_at = now()
    where sync_id = p_sync_id;
  else
    update public.cliente_contact_sync_outbox
    set estado = case when attempts >= 5 then 'DEAD' else 'FAILED' end,
        lease_until = null,
        next_retry_at = case
          when attempts >= 5 then null
          else now() + make_interval(secs => least(greatest(coalesce(p_retry_seconds, 300), 60), 86400))
        end,
        last_error = left(coalesce(p_error, 'GOOGLE_CONTACTS_SYNC_FAILED'), 2000),
        updated_at = now()
    where sync_id = p_sync_id;
  end if;

  select * into v_row from public.cliente_contact_sync_outbox where sync_id = p_sync_id;
  return jsonb_build_object(
    'sync_id', v_row.sync_id,
    'cliente_id', v_row.cliente_id,
    'estado', v_row.estado,
    'attempts', v_row.attempts,
    'next_retry_at', v_row.next_retry_at,
    'resource_name', v_row.resource_name
  );
end;
$$;

revoke all on function public.caja_contact_sync_finish_v1(bigint,boolean,text,text,integer) from public, anon, authenticated;
grant execute on function public.caja_contact_sync_finish_v1(bigint,boolean,text,text,integer) to service_role;

-- PRE-CHECK después de aplicar:
-- select to_regclass('public.cliente_form_ingestas'),
--        to_regclass('public.cliente_contact_sync_outbox');
--
-- Smoke test recomendado: ejecutar caja_ingestar_cliente_form_v1 dentro de
-- BEGIN/ROLLBACK con un E.164 de QA y verificar que solo los CANONICO generan outbox.
